// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.7.3'
        classpath 'com.google.gms:google-services:4.4.2'
    }
}

apply from: "variables.gradle"

allprojects {
    repositories {
        google()
        mavenCentral()
    }
    configurations.all {
        resolutionStrategy {
            force 'androidx.core:core:1.15.0'
            force 'androidx.core:core-ktx:1.15.0'
            force 'androidx.appcompat:appcompat:1.7.0'
        }
    }
    tasks.whenTaskAdded { task ->
        if (task.name.startsWith('check') && task.name.endsWith('AarMetadata')) {
            task.enabled = false
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
