-- ==============================================================================
-- SCHEMA DEDICADO: REGISTROS DE NÍVEL DE ÓLEO DO MOTOR (FLEET OPERAÇÃO)
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.registros_nivel_oleo (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo_registro VARCHAR(50) NOT NULL UNIQUE,       -- Ex: 'ALP.O-2026-0001'
  placa VARCHAR(10) NOT NULL,
  regional VARCHAR(50),
  
  -- Nível: 1 = Normal, 2 = Baixo, 3 = Sem Óleo
  nivel_oleo SMALLINT NOT NULL CHECK (nivel_oleo IN (1, 2, 3)),
  nivel_oleo_rotulo VARCHAR(30) NOT NULL,            -- 'Normal', 'Baixo', 'Sem Óleo'
  
  -- Hodômetro na aferição
  hodometro INTEGER NOT NULL CHECK (hodometro >= 0),
  
  -- 3 Evidências Fotográficas Obrigatórias
  foto_frente_url TEXT NOT NULL,
  foto_hodometro_url TEXT NOT NULL,
  foto_haste_url TEXT NOT NULL,
  
  observacoes TEXT,
  
  -- Status do ciclo de vida
  status VARCHAR(30) NOT NULL DEFAULT 'REGISTRADO' 
    CHECK (status IN ('REGISTRADO', 'CHAMADO_ABERTO', 'RESOLVIDO', 'CANCELADO')),
    
  -- Vínculo com a Ordem de Serviço / Chamado de Manutenção
  chamado_id BIGINT,
  chamado_codigo VARCHAR(50),
  data_hora_chamado_aberto TIMESTAMPTZ,
  aberto_por_operador VARCHAR(150),
  
  -- Auditoria
  criado_por VARCHAR(150) NOT NULL,
  criado_por_id VARCHAR(100),
  data_registro TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Índices e RLS
CREATE INDEX IF NOT EXISTS idx_reg_oleo_placa ON public.registros_nivel_oleo (placa);
CREATE INDEX IF NOT EXISTS idx_reg_oleo_status ON public.registros_nivel_oleo (status);
CREATE INDEX IF NOT EXISTS idx_reg_oleo_nivel ON public.registros_nivel_oleo (nivel_oleo);
CREATE INDEX IF NOT EXISTS idx_reg_oleo_data ON public.registros_nivel_oleo (data_registro DESC);

ALTER TABLE public.registros_nivel_oleo ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir leitura para todos em registros_nivel_oleo" ON public.registros_nivel_oleo FOR SELECT USING (true);
CREATE POLICY "Permitir inserção e atualização em registros_nivel_oleo" ON public.registros_nivel_oleo FOR ALL USING (true);
CREATE POLICY "Permitir exclusão em registros_nivel_oleo" ON public.registros_nivel_oleo FOR DELETE USING (true);
GRANT ALL ON TABLE public.registros_nivel_oleo TO anon, authenticated;

-- Habilitar Realtime WebSocket do Supabase para a tabela
ALTER PUBLICATION supabase_realtime ADD TABLE public.registros_nivel_oleo;
